# @baseUrl = http://localhost:8000/api
@baseUrl = http://103.31.38.186/api
@token = {{login.response.body.token}}

### Register a new user
# @name register
POST {{baseUrl}}/register
Content-Type: application/json

{
    "name": "John Doe",
    "username": "johndoe",
    "email": "john@example.com",
    "password": "password123",
    "project": "DOC-SYS",
    "department_id": 1
}

### Get authenticated user
GET {{baseUrl}}/user
Authorization: Bearer {{token}}

### Login with superadmin credentials
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "login": "superadmin",
    "password": "654321"
}

### Login with regular user credentials
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "user",
    "password": "654321"
}

### Logout user
POST {{baseUrl}}/logout
Authorization: Bearer {{token}}

### Get authenticated user
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}




